require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe CompanyProfilesController do

  def mock_company_profile(stubs={})
    @mock_company_profile ||= mock_model(CompanyProfile, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all company_profiles as @company_profiles" do
      CompanyProfile.stub(:all) { [mock_company_profile] }
      get :index
      assigns(:company_profiles).should eq([mock_company_profile])
    end
  end

  describe "GET show" do
    it "assigns the requested company_profile as @company_profile" do
      CompanyProfile.stub(:find).with("37") { mock_company_profile }
      get :show, :id => "37"
      assigns(:company_profile).should be(mock_company_profile)
    end
  end

  describe "GET new" do
    it "assigns a new company_profile as @company_profile" do
      CompanyProfile.stub(:new) { mock_company_profile }
      get :new
      assigns(:company_profile).should be(mock_company_profile)
    end
  end

  describe "GET edit" do
    it "assigns the requested company_profile as @company_profile" do
      CompanyProfile.stub(:find).with("37") { mock_company_profile }
      get :edit, :id => "37"
      assigns(:company_profile).should be(mock_company_profile)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created company_profile as @company_profile" do
        CompanyProfile.stub(:new).with({'these' => 'params'}) { mock_company_profile(:save => true) }
        post :create, :company_profile => {'these' => 'params'}
        assigns(:company_profile).should be(mock_company_profile)
      end

      it "redirects to the created company_profile" do
        CompanyProfile.stub(:new) { mock_company_profile(:save => true) }
        post :create, :company_profile => {}
        response.should redirect_to(company_profile_url(mock_company_profile))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved company_profile as @company_profile" do
        CompanyProfile.stub(:new).with({'these' => 'params'}) { mock_company_profile(:save => false) }
        post :create, :company_profile => {'these' => 'params'}
        assigns(:company_profile).should be(mock_company_profile)
      end

      it "re-renders the 'new' template" do
        CompanyProfile.stub(:new) { mock_company_profile(:save => false) }
        post :create, :company_profile => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested company_profile" do
        CompanyProfile.stub(:find).with("37") { mock_company_profile }
        mock_company_profile.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :company_profile => {'these' => 'params'}
      end

      it "assigns the requested company_profile as @company_profile" do
        CompanyProfile.stub(:find) { mock_company_profile(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:company_profile).should be(mock_company_profile)
      end

      it "redirects to the company_profile" do
        CompanyProfile.stub(:find) { mock_company_profile(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(company_profile_url(mock_company_profile))
      end
    end

    describe "with invalid params" do
      it "assigns the company_profile as @company_profile" do
        CompanyProfile.stub(:find) { mock_company_profile(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:company_profile).should be(mock_company_profile)
      end

      it "re-renders the 'edit' template" do
        CompanyProfile.stub(:find) { mock_company_profile(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested company_profile" do
      CompanyProfile.stub(:find).with("37") { mock_company_profile }
      mock_company_profile.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the company_profiles list" do
      CompanyProfile.stub(:find) { mock_company_profile }
      delete :destroy, :id => "1"
      response.should redirect_to(company_profiles_url)
    end
  end

end
